[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-awesome-app"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.13.1",
    "flwr-datasets[vision]>=0.3.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
    "numpy<2.0.0",
    "wandb (>=0.19.5,<0.20.0)",
    "toml (>=0.10.2,<0.11.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "hydra-core (>=1.3.2,<2.0.0)",
]

requires-python = ">=3.10,<3.11"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "jionnnas"

[tool.flwr.app.components]
serverapp = "flower.server_app:app"
clientapp = "flower.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 50 # number of rounds for the server (shokri used 100 but with central training)
local-epochs = 20 # clients train for 1 epoch per round
learning-rate = 0.01 # shokri used 0.001
learning-rate-decay = 1e-7 # shokri used 1e-7
weight-decay = 0.0 # shokri used 0.0, 5e-4 is common for federated learning
batch-size = 32
fraction-fit = 1.0  # all clients participate in each round
device = "cuda" # <-- "cpu" or "cuda"
# loader defined in utils.model_factory.create_model
model = "simple_model" # <-- simple_model, simple_model_with_dropout, complex_model, complex_model_with_dropout
train-target-model-as-shadow-model = false
seed = 42
iid-data-distribution = true # if true, data is distributed iid among clients
dirichlet-alpha = 0.5 # if iid_data_distribution is false, this is the dirichlet alpha parameter (0.1 -> strong non_iid, 0.5-> add bias to data)
num-clients = 4 # number of clients only for visualization purposes, not used in the run

[tool.flwr.federations]
default = "local-simulation-gpu"  # default setting for local simulation

[tool.flwr.federations.local-simulation-cpu] # cpu simulation
options.num-supernodes = 4 # number of simulated clients
options.backend.client-resources.num-cpus = 1

[tool.flwr.federations.local-simulation-gpu] # gpu simulation
options.num-supernodes = 4 # number of simulated clients
options.backend.client-resources.num-cpus = 1
options.backend.client-resources.num-gpus = 0.25  # 25% VRAM pro Client
# options.backend.init_args.num_cpus = 1 # maximum number of CPUs for the simulation
# options.backend.init_args.num_gpus = 1 # maximum number of GPUs for the simulation