parameters:
  num_classes: 10
  num_shadow_models: 1
  # loader defined in tasks.create_model()
  model_arch: "simple_model" # <-- simple_model, simple_model_with_dropout, complex_model, complex_model_with_dropout
  shadow_epochs: 40
  train_size: 100 # Size of train/test sets for shadow models (>15.000 samples would be with duplicates)
  test_size: 100
  weight_decay: 0.0  # shokri used 0.0, 5e-4 is common for federated learning


parameters_static:
  device: "cuda"  # <-- "cpu" or "cuda"
  seed: 42
  batch_size: 32
  learning_rate_decay: 1e-7
  learning_rate: 0.05
  num_workers: 2
  class_names: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


paths:
  target_checkpoint_dir: "model_checkpoints_target"
  split_dir: "splits" # directory should lay in root