num_server_rounds: 100 # 100, 20, 10
local_epochs: 1 # 1, 5, 10
learning_rate: 0.01  # test if works
learning_rate_decay: 1e-7
batch_size: 128
fraction_fit: 1.0 # maybe testing
device: "cuda"
weight_decay: 0.0 # 0,0 or 5e-4
model: "simple_model" # simple_model, simple_model_with_dropout, complex_model, complex_model_with_dropout
seed: 42
iid_data_distribution: true # true, false
dirichlet_alpha: 0.0 # if false, 0.5, 0.1
num_clients: 8
